// Copyright PJGame. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace PJGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Damage_Applied);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Actor_Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Caravan_Destroyed);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Physical);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Ice);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Rolling);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Stunned);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Roll);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Interact);
}
